name: mediumm
description: "A Medium-inspired Flutter app with rich features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  # State management for reactive UI
  provider:
  # Networking for API calls (e.g., fetching articles)
  http:
  # Firebase for authentication and backend storage
  firebase_core:
  firebase_auth:
  cloud_firestore:
  # Rich text editor for writing articles
  flutter_quill:
  # Image picking and uploading (e.g., for article covers)
  image_picker:
  # Cached network images for smooth loading
  cached_network_image:
  shimmer:
  #ui
  google_nav_bar:
  # Animations for a polished UX
  flutter_staggered_animations:
  # Offline support and local storage
  hive:
  hive_flutter:
  get_storage:
  flutter_bouncing_widgets:
  get:
  flutter_markdown:

  pull_to_refresh:
  # Creative UI enhancements
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Build runner for Hive code generation
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
